name: Dependency Check
on:
  push:
    branches:
      - master

jobs:
  check-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Run Gradle Dependency Submission
        uses: mikepenz/gradle-dependency-submission@latest
        with:
          gradle-build-module: ':'
          gradle-build-configuration: 'compileClasspath'
